'use client';
import {useEffect,useState} from 'react';
import {contentKeys,type ContentKey,type SiteContent} from '@/lib/site-content';
type Value=string|number|boolean|null|Value[]|{[key:string]:Value};
const sections:Record<ContentKey,string>={appearance:'Aparência',course:'Curso',strategies:'Estratégias',macro:'Notícias e calendário'};
const labels:Record<string,string>={calendarUpdatedAt:'Data de verificação do calendário (Brasília)',impact:'Impacto potencial',assets:'Ativos relacionados',explanation:'O que é este evento',favorable:'Cenário que pode favorecer a moeda',unfavorable:'Cenário que pode pressionar a moeda',caution:'O que observar no gráfico',previous:'Valor anterior (com referência)',forecast:'Consenso de mercado (se verificado)',actual:'Resultado (se verificado)',previousSource:'Fonte do valor anterior',forecastSource:'Fonte do consenso',actualSource:'Fonte do resultado',name:'Nome',tagline:'Assinatura',headline:'Título da tela de login',description:'Descrição',background:'Fundo',accent:'Cor de destaque',title:'Título',status:'Situação do curso',about:'Sobre o curso',modules:'Módulos',lessons:'Aulas',videoUrl:'Link do vídeo (opcional)',materialUrl:'Link do material (opcional)',items:'Estratégias',rules:'Regras e exemplos',updatedAt:'Data de verificação da edição (Brasília)',weekStart:'Início da edição',weekEnd:'Fim da edição',heading:'Título da edição',summary:'Resumo',comparison:'Comparação dólar × euro',news:'Notícias',scenarios:'Cenários',events:'Eventos econômicos',notes:'Notas da edição',date:'Data',tag:'Categoria',watch:'O que acompanhar',source:'Fonte',label:'Nome da fonte',url:'Link da fonte',currency:'Moeda',rate:'Taxa de referência',rateLabel:'Nome da taxa',asOf:'Data de referência',facts:'Fatos publicados',interpretation:'Interpretação',sources:'Fontes',at:'Horário do evento (Brasília; deixe vazio se não confirmado)',why:'Por que acompanhar'};
const source={label:'',url:''};
function template(key:string):Value{
 const day=new Date().toISOString().slice(0,10);
 switch(key){
  case 'modules':return {title:'Novo módulo',description:'',lessons:[]};
  case 'lessons':return {title:'Nova aula',videoUrl:'',materialUrl:''};
  case 'news':return {id:crypto.randomUUID(),date:day,tag:'USD / EUR',title:'Nova notícia',summary:'',watch:'',source:{...source}};
  case 'events':return {id:crypto.randomUUID(),title:'Novo evento',currency:'USD',date:day,at:null,source:{...source},why:'',impact:'Não classificado',assets:[],explanation:'',favorable:'',unfavorable:'',caution:'',previous:'',forecast:'',actual:'',previousSource:{...source},forecastSource:{...source},actualSource:{...source}};
  case 'sources':return {...source};
  default:return '';
 }
}
const longFields=['description','about','rules','summary','comparison','watch','facts','interpretation','why','notes','explanation','favorable','unfavorable','caution'];
function localTime(value:string){return Number.isNaN(Date.parse(value))?'':new Date(Date.parse(value)-3*3600000).toISOString().slice(0,16);}
function Fields({value,onChange,name='',path='',disabled=false}:{value:Value;onChange:(v:Value)=>void;name?:string;path?:string;disabled?:boolean}){
 const label=labels[name]||name;
 if(Array.isArray(value))return <section className="admin-list"><h3>{label}</h3>{value.map((item,i)=><div className="admin-item" key={i}><div className="admin-item-head"><b>{label} · {i+1}</b>{!['items','scenarios'].includes(name)&&<button type="button" disabled={disabled} onClick={()=>{if(confirm('Remover este item do rascunho? A remoção só será publicada ao salvar.'))onChange(value.filter((_,j)=>j!==i));}}>Remover</button>}</div><Fields name={name==='notes'?'notes':''} value={item} path={path+'.'+i} disabled={disabled} onChange={next=>onChange(value.map((x,j)=>j===i?next:x))}/></div>)}{!['items','scenarios'].includes(name)&&<button type="button" className="admin-secondary" disabled={disabled} onClick={()=>onChange([...value,template(name)])}>+ Adicionar {label.toLowerCase()}</button>}</section>;
 if(value!==null&&typeof value==='object')return <div className="admin-fields">{Object.entries(value).filter(([k])=>k!=='id').map(([key,v])=><Fields key={key} name={key} path={path+'.'+key} value={v} disabled={disabled} onChange={next=>onChange({...value,[key]:next})}/>)}</div>;
 const id='field'+path;
 if(name==='at'||name==='updatedAt'||name==='calendarUpdatedAt')return <label htmlFor={id}>{label}<input id={id} type="datetime-local" disabled={disabled} value={value?localTime(String(value)):''} required={name!=='at'} onChange={e=>onChange(e.target.value?new Date(e.target.value+':00-03:00').toISOString():null)}/></label>;
 const choices=name==='impact'?{'Alto':'Alto','Moderado':'Moderado','Baixo':'Baixo','Não classificado':'Não classificado'}:name==='background'?{black:'Preto intenso',graphite:'Grafite'}:name==='accent'?{orange:'Laranja',gold:'Dourado',mint:'Verde'}:name==='currency'?{USD:'Dólar (USD)',EUR:'Euro (EUR)'}:null;
 if(choices)return <label htmlFor={id}>{label}<select id={id} disabled={disabled} value={String(value)} onChange={e=>onChange(e.target.value)}>{Object.entries(choices).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
 const locked=name==='name'&&path.startsWith('strategies');
 return <label htmlFor={id}>{label}{longFields.includes(name)?<textarea id={id} disabled={disabled} rows={4} maxLength={12000} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>:<input id={id} readOnly={locked} disabled={disabled} type={['date','weekStart','weekEnd','asOf'].includes(name)?'date':name.toLowerCase().includes('url')?'url':'text'} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}</label>;
}
export default function AdminEditor({initial,initialRevisions}:{initial:SiteContent;initialRevisions:Record<string,number>}){
 const [content,setContent]=useState(initial),[revisions,setRevisions]=useState(initialRevisions),[active,setActive]=useState<ContentKey>('appearance'),[dirty,setDirty]=useState<Partial<Record<ContentKey,boolean>>>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const unsaved=Object.values(dirty).some(Boolean);
 useEffect(()=>{if(!unsaved)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[unsaved]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/admin/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:active,payload:content[active],revision:revisions[active]||0})});const result=await r.json();if(!r.ok)throw Error(result.error||'Não foi possível publicar.');setRevisions(v=>({...v,[active]:result.revision}));setDirty(v=>({...v,[active]:false}));setMessage('Publicado. A alteração aparecerá ao abrir ou atualizar o site.');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <main className="admin-page"><header><div><small>MÉTODO DOS QUADRANTES</small><h1>Administração</h1><p>Edite o conteúdo do site. Seus rascunhos só entram no ar ao publicar.</p></div><a href="/" onClick={e=>{if(unsaved&&!confirm('Há alterações não publicadas. Sair sem salvar?'))e.preventDefault();}}>← Voltar ao diário</a></header><nav aria-label="Seções administrativas">{contentKeys.map(k=><button key={k} disabled={saving} className={active===k?'selected':''} onClick={()=>{setActive(k);setError('');setMessage('');}}>{sections[k]}{dirty[k]?' •':''}</button>)}</nav><form onSubmit={save}><div className="admin-section-heading"><h2>{sections[active]}</h2><span>{dirty[active]?'Alterações não publicadas':'Conteúdo atual'}</span></div>{active==='macro'&&<p className="admin-help">Mantenha as datas reais de verificação e os links das fontes. Os horários são informados em Brasília. Os dados COT continuam vindo da CFTC e não são editados aqui.</p>}{active==='course'&&<p className="admin-help">Adicione links HTTPS dos vídeos e materiais. As aulas abrem em outra aba; envie os arquivos primeiro ao seu serviço de hospedagem.</p>}{active==='strategies'&&<p className="admin-help">Edite as regras e exemplos dos três setups. Os nomes permanecem iguais para preservar a classificação das operações.</p>}<Fields value={content[active] as Value} name={active} path={active} disabled={saving} onChange={v=>{setContent(c=>({...c,[active]:v} as SiteContent));setDirty(d=>({...d,[active]:true}));setMessage('');}}/>{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-success" role="status">{message}</p>}<div className="admin-actions"><span>Publicar atualiza esta seção para todos os usuários.</span><button className="admin-primary" disabled={saving||!dirty[active]}>{saving?'Publicando…':'Salvar e publicar'}</button></div></form></main>;
}
