'use client';
import {GraduationCap,Clapperboard,BookOpen,ArrowRight} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
const modules=[
 {title:'Fundamentos e leitura de mercado',description:'Uma base para compreender o contexto antes de pensar na entrada.',lessons:['Estrutura de mercado e Teoria de Dow','Topos, fundos e tendências']},
 {title:'Construindo os quadrantes',description:'Organização das regiões de preço usadas no método.',lessons:['Marcação do quadrante: topo, fundo e equilíbrio','Níveis de 25%, 50% e 75% e projeções']},
 {title:'Contexto, liquidez e zonas de impacto',description:'Leitura do cenário e das regiões que merecem atenção.',lessons:['Acumulação e distribuição','Liquidez e confluências nas zonas de impacto']},
 {title:'Da análise à execução',description:'Planejamento da operação e critérios de confirmação.',lessons:['Rompimento, reteste e pullback','Candles de força e padrões de confirmação']},
 {title:'Gerenciamento e disciplina',description:'Regras para cuidar do capital e revisar suas decisões.',lessons:['Risco, stop e alvo antes da entrada','Emoções e aderência ao plano']},
 {title:'Prática e diário do trader',description:'Registro e revisão para acompanhar a evolução do processo.',lessons:['Estudo de operações no gráfico','Revisão das operações no Quadrantes Journal']},
];
export default function Course({onJournal}:{onJournal:()=>void}){return <div className="course-area"><section className="course-intro panel"><div className="course-mark"><GraduationCap size={32}/></div><div><span className="course-status">Em preparação</span><h2>Aprenda a ler o mercado.</h2><p>Gerenciamento, disciplina e técnica na aplicação do Método dos Quadrantes.</p></div></section><div className="course-layout"><section className="panel course-syllabus"><div className="panel-head"><div><h2>Trilha de aprendizado</h2><p>Estrutura inicial sugerida · 6 módulos</p></div><BookOpen size={20}/></div><Accordion type="single" collapsible defaultValue="module-0">{modules.map((module,i)=><AccordionItem value={'module-'+i} key={module.title}><AccordionTrigger className="course-module-trigger"><span className="strategy-number">{String(i+1).padStart(2,'0')}</span><span className="course-module-name">{module.title}<small>2 aulas previstas</small></span></AccordionTrigger><AccordionContent className="course-module-content"><p>{module.description}</p><ul>{module.lessons.map((lesson,j)=><li key={lesson}><Clapperboard size={17}/><span><small>Aula {i+1}.{j+1}</small>{lesson}</span><span className="lesson-status">Em preparação</span></li>)}</ul></AccordionContent></AccordionItem>)}</Accordion></section><aside className="course-aside"><section className="panel"><GraduationCap size={24}/><h2>Sobre o curso</h2><p>Esta área reunirá as aulas do Método dos Quadrantes.</p><p>Os vídeos e materiais ainda não estão disponíveis. A organização dos módulos poderá ser ajustada antes do lançamento.</p></section><section className="panel"><BookOpen size={24}/><h2>Seu aprendizado na prática</h2><p>O diário já está disponível para registrar suas operações, emoções e aprendizados.</p><button className="secondary" onClick={onJournal}>Abrir meu diário <ArrowRight size={16}/></button></section></aside></div></div>}
