'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,Clock3,ArrowUpRight,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {EconomicEvent,MacroBrief,SourceLink} from '@/lib/macro-types';
import {brazilDay,filterEvents,eventStatus,calendarZone} from '@/lib/economic-calendar';
const shortDate=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:calendarZone,day:'2-digit',month:'2-digit'});
const time=(at:string|null)=>at?new Date(at).toLocaleTimeString('pt-BR',{timeZone:calendarZone,hour:'2-digit',minute:'2-digit'}):'A confirmar';
function Source({value}:{value:SourceLink}){return <a className="macro-source" href={value.url} target="_blank" rel="noopener noreferrer">{value.label}<ArrowUpRight size={13}/></a>}
export default function EconomicCalendar({brief}:{brief:MacroBrief}){
 const [now,setNow]=useState<number|null>(null),[period,setPeriod]=useState('Esta semana'),[currency,setCurrency]=useState('Todas'),[high,setHigh]=useState(false),[selected,setSelected]=useState<EconomicEvent|null>(null);
 useEffect(()=>{setNow(Date.now());const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[]);
 const rows=now===null?[]:filterEvents(brief.events,brazilDay(now),period,currency,high);
 const next=now===null?undefined:[...brief.events].filter(e=>e.at&&Date.parse(e.at)>now&&(currency==='Todas'||e.currency===currency)&&(!high||e.impact==='Alto')).sort((a,b)=>a.at!.localeCompare(b.at!))[0];
 const verified=brief.calendarUpdatedAt||brief.updatedAt;
 return <section className="economic-calendar"><div className="econ-heading"><div><span className="eyebrow">PREPARE SEU DIA</span><h2>Calendário econômico</h2><p>Saiba quando acontece e entenda o que pode mudar.</p></div><span className="econ-zone"><Clock3 size={15}/> Horário de Brasília</span></div>
 {next&&<button className="econ-next" onClick={()=>setSelected(next)}><CalendarDays size={23}/><span><small>PRÓXIMO EVENTO CADASTRADO</small><b>{next.title}</b></span><strong>{shortDate(next.date)} · {time(next.at)}</strong><ChevronRight size={20}/></button>}
 <div className="econ-filters"><div role="group" aria-label="Período do calendário">{['Hoje','Esta semana','Próximos 14 dias','Todos'].map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div><label>Moeda <select value={currency} onChange={e=>setCurrency(e.target.value)}><option>Todas</option><option>USD</option><option>EUR</option></select></label><label className="econ-check"><input type="checkbox" checked={high} onChange={e=>setHigh(e.target.checked)}/>Somente alto impacto</label></div>
 <div className="panel econ-table-wrap"><table className="econ-table"><caption className="sr-only">Eventos econômicos, horários de Brasília e impacto potencial</caption><thead><tr><th>Data e hora</th><th>Moeda</th><th>Evento</th><th>Impacto potencial</th><th>Ativos relacionados</th><th>Detalhes</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><b>{time(e.at)}</b><small>{shortDate(e.date)}</small></td><td><span className="econ-currency">{e.currency}</span></td><td><button className="econ-event-name" onClick={()=>setSelected(e)}>{e.title}</button><small>{eventStatus(e,now!)}</small></td><td><span className={'econ-impact '+(e.impact==='Alto'?'high':e.impact==='Moderado'?'medium':'low')}>{e.impact||'Não classificado'}</span></td><td>{e.assets?.length?e.assets.join(' · '):'Não informados'}</td><td><button className="econ-detail-button" onClick={()=>setSelected(e)} aria-label={'Entender '+e.title}>Entender <ChevronRight size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="econ-empty"><CalendarDays/><h3>{now===null?'Carregando agenda…':'Nenhum evento nesta seleção'}</h3><p>Esta é uma agenda selecionada, não uma lista de todas as notícias do mercado.</p>{now!==null&&<button onClick={()=>{setPeriod('Próximos 14 dias');setCurrency('Todas');setHigh(false)}}>Ver próximos 14 dias</button>}</div>}</div>
 <p className="econ-footnote">Agenda verificada em {new Date(verified).toLocaleString('pt-BR',{timeZone:calendarZone})}. Impacto é uma classificação editorial de atenção, não uma previsão de direção. Resultados não são atualizados em tempo real.</p>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="econ-dialog"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected&&`${selected.currency} · ${shortDate(selected.date)} · ${time(selected.at)} (Brasília)`}</DialogDescription>{selected&&<div className="econ-detail"><div className="econ-plain"><h3>O que é?</h3><p>{selected.explanation||selected.why}</p><h3>Por que importa?</h3><p>{selected.why}</p></div><div className="econ-values">{([['Anterior',selected.previous,selected.previousSource],['Expectativa do mercado',selected.forecast,selected.forecastSource],['Resultado',selected.actual,selected.actualSource]] as const).map(([label,value,source])=><div key={label}><small>{label}</small><b>{value||'Não verificado'}</b>{source?.url&&<Source value={source}/>}</div>)}</div><h3>Cenários possíveis · interpretação</h3><div className="econ-scenarios"><article><span>↗ Pode favorecer {selected.currency}</span><p>{selected.favorable||'Ainda não há uma leitura editorial verificada para este evento.'}</p></article><article><span>↘ Pode pressionar {selected.currency}</span><p>{selected.unfavorable||'Compare o resultado com a expectativa e acompanhe a reação dos preços.'}</p></article></div><p className="econ-disclaimer">A reação depende da surpresa em relação ao consenso, das revisões e do contexto. Não há uma probabilidade numérica calculada nem garantia de direção.</p><div className="econ-quadrants"><h3>No Método dos Quadrantes</h3><p>{selected.caution||'Use a notícia como contexto. Observe se o preço sustenta ou rejeita sua região e espere a confirmação prevista no seu setup.'}</p></div><Source value={selected.source}/></div>}</DialogContent></Dialog>
 </section>;
}
