'use client';
import {useState} from 'react';
import {Calculator} from 'lucide-react';
import {forexPosition} from '@/lib/forex-position';
const pairs=['EURUSD','GBPUSD','AUDUSD','NZDUSD','USDJPY','USDCHF','USDCAD','EURGBP','EURJPY','GBPJPY','AUDJPY','CHFJPY','EURNZD'];
const usd=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD'}).format(v);
export default function ForexCalculator({capital,riskPercent}:{capital:number;riskPercent:number}){
 const [pair,setPair]=useState('EURUSD'),[stop,setStop]=useState(''),[conversion,setConversion]=useState(''),[contract,setContract]=useState('100000'),[step,setStep]=useState('0.01'),[minimum,setMinimum]=useState('0.01');
 const quote=pair.slice(3),pipSize=quote==='JPY'?0.01:0.0001;
 const result=forexPosition({capital,riskPercent,stopPips:Number(stop),quoteToUsd:quote==='USD'?1:Number(conversion),pipSize,contract:Number(contract),step:Number(step),minimum:Number(minimum)});
 return <section className="panel forex-calculator"><div className="panel-head"><div><h2>Calculadora de lotes Forex</h2><p>Quanto operar para respeitar o risco do seu plano?</p></div><Calculator/></div><div className="forex-body"><p>Conta em <b>USD</b> · Capital {usd(capital)} · Risco {riskPercent}%<br/><small>Usa os valores do plano acima. Esta simulação não envia ordens.</small></p><div className="forex-fields"><label>Par de moedas<select value={pair} onChange={e=>{setPair(e.target.value);setConversion('')}}>{pairs.map(p=><option key={p}>{p}</option>)}</select></label><label>Distância até o stop (pips)<input type="number" min="0.01" step="any" placeholder="Ex.: 20" value={stop} onChange={e=>setStop(e.target.value)}/><small>1 pip = {pipSize}. Não confunda pips com pontos do MT5.</small></label>{quote!=='USD'&&<label>1 {quote} vale quantos USD?<input type="number" min="0" step="any" placeholder="Informe a conversão atual" value={conversion} onChange={e=>setConversion(e.target.value)}/><small>Use a cotação atual da corretora. Se USD/{quote} = X, informe 1 ÷ X. Conversão manual, sem preço ao vivo.</small></label>}</div><details className="forex-settings"><summary>Especificações da corretora</summary><div className="forex-fields"><label>Unidades por lote<input type="number" min="1" step="1" value={contract} onChange={e=>setContract(e.target.value)}/></label><label>Passo de volume (lotes)<input type="number" min="0.001" step="0.001" value={step} onChange={e=>setStep(e.target.value)}/></label><label>Lote mínimo<input type="number" min="0.001" step="0.001" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label></div><p>Confira tamanho do contrato, volume mínimo e passo nas especificações do símbolo no MT5.</p></details><div className="forex-result" aria-live="polite">{result?<><div><span>VOLUME CALCULADO</span><strong>{result.belowMinimum?'Abaixo do mínimo':result.lots.toLocaleString('pt-BR',{maximumFractionDigits:8})+' lotes'}</strong></div>{result.belowMinimum?<p>O lote mínimo ultrapassaria seu risco. Não arredondamos o volume para cima.</p>:<div className="forex-metrics"><p>Risco estimado no stop <b>{usd(result.risk)}</b></p><p>Limite planejado <b>{usd(result.budget)}</b></p><p>Valor do pip por lote <b>{usd(result.pipValue)}</b></p><p>Volume em {pair.slice(0,3)} <b>{result.units.toLocaleString('pt-BR',{maximumFractionDigits:2})}</b></p></div>}</>:<p>Preencha o stop{quote!=='USD'?' e a conversão para USD':''} com valores positivos para calcular. Confira também os valores do plano.</p>}</div><p className="forex-note">Volume arredondado para baixo. Estimativa sem spread, comissão, swap ou slippage; a perda real pode ser maior. A margem disponível também precisa ser conferida na corretora. Exclusivo para pares Forex, não se aplica a ouro, índices ou cripto.</p><a className="forex-source" href="https://help.oanda.com/us/en/faqs/micro-lots.htm" target="_blank" rel="noopener noreferrer">Entenda lotes e unidades ↗</a></div></section>;
}
